permalink: /:year/:month/:day/:title.html
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: Owen
  #email:469564715@qq.com
  link: http://Owen.org
  #weibo: http://weibo.com/yansu0711
  github: http://github.com/NumerHero

# 站点信息
title: 欧阳湘粤的博客 
description: 欧阳湘粤的博客
url: http://Owen.org
rss_url: /pages/atom.xml

# avatar头像及Favicon
#avatar: 
#favicon: 

# google analytics 设置
ga:
  id: UA-54767140-1
  url: yansu.org

# disqus 设置
disqus:
  shortname: Owen-Lavender