permalink: /:year/:month/:day/:title.html
markdown: kramdown
Rouge: true

kramdown:
  input: GFM
  use_coderay: true

# 作者信息
author: 
name: Owen
email: 469564715@qq.com
link: http://Owen.org
#weibo: 
github: http://github.com/NumerHero

# 站点信息
title: 仰望星空的天台 
description: 欧阳湘粤的博客
url: http://Owen.org
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: file://url(../assets/img/avatar.png) 
favicon: file://url(../assets/img/corazón.ico)

# google analytics 设置
ga:
  id: UA-54767140-1
  url: yansu.org

# disqus 设置
disqus:
  shortname: Owen-Lavender