permalink: /:year/:month/:day/:title.html

highlighter: pygments
markdown: kramdown  # [ maruku | rdiscount | kramdown | redcarpet ]
kramdown:
  input:         GFM
  auto_ids:      true
#  auto_id_prefix:'id-'
  # footnote_nr:   1
  # entity_output: as_char
  # toc_levels:    1..6
  # smart_quotes:  lsquo,rsquo,ldquo,rdquo
  # use_coderay:   true

  # coderay:
  #   coderay_wrap:              div
  #   coderay_line_numbers:      inline
  #   coderay_line_number_start: 1
  #   coderay_tab_width:         2
  #   coderay_bold_every:        10
  #   coderay_css:               style

# 作者信息
author: 
name: Owen
email: 469564715@qq.com
link: http://Owen.org
#weibo: 
github: http://github.com/NumerHero

# 站点信息
title: Owen的博客 
description: 欧阳湘粤的博客
url: http://Owen.org
rss_url: /pages/atom.xml

# google analytics 设置
ga:
  id: UA-54767140-1
  url: yansu.org

# disqus 设置
disqus:
  shortname: owen